Vagrant.configure("2") do |config|
    config.vm.box = "debian/bullseye64" 
  
    # Web Server
    config.vm.define "web" do |web|
      web.vm.hostname = "web"
      web.vm.network "private_network", ip: "192.168.56.10"
      web.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 1
      end
    end
  
    # Docker Node
    config.vm.define "docker" do |docker|
      docker.vm.hostname = "docker"
      docker.vm.network "private_network", ip: "192.168.56.11"
      docker.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 1
      end
    end
  
    # Provision
    config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y python3 python3-pip
    SHELL
  end
  