---
- name: Create user and setup SSH keys
  hosts: all
  vars:
    user: username
  become: true
  tasks:
    - name: Ensure user '{{ user }}' exists
      user:
        name: '{{ user }}'
        shell: /bin/bash
        create_home: yes

    - name: Create .ssh directory
      file:
        path: '/home/{{ user }}/.ssh'
        state: directory
        mode: '0700'
        owner: '{{ user }}'
        group: '{{ user }}'

    - name: Upload public key
      copy:
        src: '../files/{{ user }}.pub'
        dest: '/home/{{ user }}/.ssh/authorized_keys'
        owner: '{{ user }}'
        group: '{{ user }}'
        mode: '0600'